language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - 2.2.2
gemfile:
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
bundler_args: --without local
