language: ruby
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/rails41.gemfile
      rvm: 2.4.1
    - gemfile: gemfiles/rails50.gemfile
      rvm: 2.1.10
    - gemfile: gemfiles/rails51.gemfile
      rvm: 2.1.10
bundler_args: --without local
before_install:
  - gem update --system
  - gem install bundler
